# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: meshtastic/aodv.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'meshtastic/aodv.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15meshtastic/aodv.proto\x12\nmeshtastic\"\x8d\x01\n\x0cRouteRequest\x12\x0f\n\x07rreq_id\x18\x01 \x01(\r\x12\x12\n\noriginator\x18\x02 \x01(\r\x12\x1a\n\x12originator_seq_num\x18\x03 \x01(\r\x12\x13\n\x0b\x64\x65stination\x18\x04 \x01(\r\x12\x14\n\x0c\x64\x65st_seq_num\x18\x05 \x01(\r\x12\x11\n\thop_count\x18\x06 \x01(\r\"p\n\nRouteReply\x12\x12\n\noriginator\x18\x01 \x01(\r\x12\x13\n\x0b\x64\x65stination\x18\x02 \x01(\r\x12\x14\n\x0c\x64\x65st_seq_num\x18\x03 \x01(\r\x12\x11\n\thop_count\x18\x04 \x01(\r\x12\x10\n\x08lifetime\x18\x05 \x01(\r\"K\n\nRouteError\x12=\n\x18unreachable_destinations\x18\x01 \x03(\x0b\x32\x1b.meshtastic.UnreachableNode\"4\n\x0fUnreachableNode\x12\x10\n\x08node_num\x18\x01 \x01(\r\x12\x0f\n\x07seq_num\x18\x02 \x01(\r\"\x8b\x01\n\x04\x41ODV\x12(\n\x04rreq\x18\x01 \x01(\x0b\x32\x18.meshtastic.RouteRequestH\x00\x12&\n\x04rrep\x18\x02 \x01(\x0b\x32\x16.meshtastic.RouteReplyH\x00\x12&\n\x04rerr\x18\x03 \x01(\x0b\x32\x16.meshtastic.RouteErrorH\x00\x42\t\n\x07variantB`\n\x14org.meshtastic.protoB\nAODVProtosZ\"github.com/meshtastic/go/generated\xaa\x02\x14Meshtastic.Protobufs\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meshtastic.aodv_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024org.meshtastic.protoB\nAODVProtosZ\"github.com/meshtastic/go/generated\252\002\024Meshtastic.Protobufs\272\002\000'
  _globals['_ROUTEREQUEST']._serialized_start=38
  _globals['_ROUTEREQUEST']._serialized_end=179
  _globals['_ROUTEREPLY']._serialized_start=181
  _globals['_ROUTEREPLY']._serialized_end=293
  _globals['_ROUTEERROR']._serialized_start=295
  _globals['_ROUTEERROR']._serialized_end=370
  _globals['_UNREACHABLENODE']._serialized_start=372
  _globals['_UNREACHABLENODE']._serialized_end=424
  _globals['_AODV']._serialized_start=427
  _globals['_AODV']._serialized_end=566
# @@protoc_insertion_point(module_scope)
