0:
  antennaGain: 0.0
  hopLimit: 3
  isClientMute: true
  isRepeater: false
  isRouter: false
  neighborInfo: false
  x: -1469.2260347789243
  y: -1050.48878235884
  z: 1.0
1:
  antennaGain: 0.0
  hopLimit: 3
  isClientMute: false
  isRepeater: false
  isRouter: false
  neighborInfo: false
  x: -2369.2260347789243
  y: -4450.48878235884
  z: 1.0
2:
  antennaGain: 0.0
  hopLimit: 3
  isClientMute: false
  isRepeater: false
  isRouter: false
  neighborInfo: false
  x: -1464.9870418833088
  y: -2981.417029195094
  z: 1.0
3:
  antennaGain: 0.0
  hopLimit: 3
  isClientMute: false
  isRepeater: false
  isRouter: false
  neighborInfo: false
  x: -366.9825505100616
  y: -1695.9792451768153
  z: 1.0
4:
  antennaGain: 0.0
  hopLimit: 3
  isClientMute: false
  isRepeater: false
  isRouter: false
  neighborInfo: false
  x: 1409.2011855348992
  y: -1282.8028145995122
  z: 1.0
5:
  antennaGain: 0.0
  hopLimit: 3
  isClientMute: false
  isRepeater: false
  isRouter: false
  neighborInfo: false
  x: 2442.617177415603
  y: -2568.240598617789
  z: 1.0
6:
  antennaGain: 0.0
  hopLimit: 3
  isClientMute: false
  isRepeater: false
  isRouter: false
  neighborInfo: false
  x: 1732.1436829976192
  y: -3991.403859495169
  z: 1.0
7:
  antennaGain: 0.0
  hopLimit: 3
  isClientMute: false
  isRepeater: false
  isRouter: false
  neighborInfo: false
  x: 892.4931895945465
  y: -5276.841643513447
  z: 1.0
8:
  antennaGain: 0.0
  hopLimit: 3
  isClientMute: false
  isRepeater: false
  isRouter: false
  neighborInfo: false
  x: -786.8077972115971
  y: -5276.841643513447
  z: 1.0
